import { DpoRecord, ResourceName, ResourceSchema } from './dpo.types';

const now = new Date('2026-07-17T12:00:00.000Z').toISOString();

export const resourceSchemas: ResourceSchema[] = [
  {
    resource: 'members',
    title: 'Members Management',
    description:
      'Approved and active DPO members with card and renewal lifecycle.',
    searchableFields: [
      'membershipNumber',
      'name',
      'cnicMasked',
      'phone',
      'district',
    ],
    filterFields: [
      'status',
      'paymentStatus',
      'country',
      'district',
      'membershipType',
    ],
    defaultSort: 'createdAt',
  },
  {
    resource: 'membership-applications',
    title: 'Membership Applications',
    description: 'Public membership applications pending review and approval.',
    searchableFields: ['applicationNumber', 'name', 'cnicMasked', 'phone'],
    filterFields: ['status', 'paymentStatus', 'country', 'district'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'membership-renewals',
    title: 'Membership Renewals',
    description: 'Membership renewal and card regeneration requests.',
    searchableFields: ['renewalNumber', 'membershipNumber', 'name'],
    filterFields: ['status', 'paymentStatus', 'district'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'membership-cards',
    title: 'Membership Cards',
    description: 'Generated, regenerated and downloadable membership cards.',
    searchableFields: ['cardNumber', 'membershipNumber', 'name'],
    filterFields: ['status', 'templateVersion'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'designation-applications',
    title: 'Designation Applications',
    description:
      'Designation applications, duplicate-area validation and approval workflow.',
    searchableFields: ['applicationNumber', 'applicant', 'designation', 'area'],
    filterFields: ['status', 'paymentStatus', 'province', 'district', 'wing'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'active-designations',
    title: 'Active Designations',
    description: 'Current designation holders and assigned areas.',
    searchableFields: ['holder', 'designation', 'area', 'membershipNumber'],
    filterFields: ['status', 'province', 'district', 'wing'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'designation-renewals',
    title: 'Designation Renewals',
    description: 'Designation renewal payment and approval workflow.',
    searchableFields: ['renewalNumber', 'holder', 'designation'],
    filterFields: ['status', 'paymentStatus', 'district'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'designation-master-list',
    title: 'Designation Master List',
    description: 'Allowed designations, amount and validity duration.',
    searchableFields: ['designation'],
    filterFields: ['status'],
    defaultSort: 'designation',
  },
  {
    resource: 'geographic-areas',
    title: 'Geographic Area Management',
    description:
      'Country, province, division, district, tehsil, union council and city hierarchy.',
    searchableFields: ['name', 'type', 'parentName'],
    filterFields: ['status', 'type', 'country', 'province'],
    defaultSort: 'name',
  },
  {
    resource: 'wireless-devices',
    title: 'Wireless Device Management',
    description:
      'IMEI, serial number, assignment, renewal, lost and blocked device workflow.',
    searchableFields: [
      'imei',
      'brand',
      'model',
      'serialNumber',
      'assignedPerson',
    ],
    filterFields: ['status', 'department'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'complaints',
    title: 'Complaint Management',
    description: 'Public complaints submitted from the frontend.',
    searchableFields: ['complaintNumber', 'name', 'phone', 'category', 'subject'],
    filterFields: ['status', 'category'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'payments',
    title: 'Payments & Finance',
    description: 'Manual transfer records and admin payment verification.',
    searchableFields: ['orderId', 'gatewayTransactionId', 'user', 'paymentType'],
    filterFields: ['status', 'gateway', 'paymentType'],
    defaultSort: 'paidDate',
  },
  {
    resource: 'welfare-campaigns',
    title: 'Welfare Campaigns',
    description:
      'Causes, campaigns, targets, publishing and cause-wise analytics.',
    searchableFields: ['title', 'cause'],
    filterFields: ['status', 'cause'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'donations',
    title: 'Donation Records',
    description: 'Donation receipts, donors, causes and payment status.',
    searchableFields: ['donorName', 'receiptNumber', 'cause'],
    filterFields: ['status', 'cause', 'paymentStatus'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'gallery-albums',
    title: 'Gallery Admin',
    description:
      'Albums, images, bilingual title, cover image, ordering and publishing.',
    searchableFields: ['titleEnglish', 'titleUrdu'],
    filterFields: ['status', 'category'],
    defaultSort: 'eventDate',
  },
  {
    resource: 'cms-pages',
    title: 'Website CMS',
    description:
      'Logo, hero slides, policies, footer, links, SEO and bilingual content.',
    searchableFields: ['slug', 'titleEnglish', 'titleUrdu'],
    filterFields: ['status', 'type'],
    defaultSort: 'slug',
  },
  {
    resource: 'card-templates',
    title: 'Card Template Management',
    description:
      'Membership and designation card front/back template versions.',
    searchableFields: ['name', 'templateType', 'version'],
    filterFields: ['status', 'templateType'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'notification-templates',
    title: 'Notification Templates',
    description:
      'Email, SMS and WhatsApp placeholder templates with variables.',
    searchableFields: ['name', 'channel', 'event'],
    filterFields: ['status', 'channel', 'event'],
    defaultSort: 'name',
  },
  {
    resource: 'notification-logs',
    title: 'Notification Logs',
    description: 'Delivery logs, failed retries and manual/bulk send history.',
    searchableFields: ['recipient', 'channel', 'event'],
    filterFields: ['status', 'channel'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'admin-users',
    title: 'Admin Users',
    description: 'Admin accounts, roles, statuses and last login.',
    searchableFields: ['name', 'email', 'role'],
    filterFields: ['status', 'role'],
    defaultSort: 'name',
  },
  {
    resource: 'roles',
    title: 'Roles & Permissions',
    description: 'Role definitions and permission matrices.',
    searchableFields: ['name', 'description'],
    filterFields: ['status'],
    defaultSort: 'name',
  },
  {
    resource: 'reports',
    title: 'Reports',
    description:
      'Report catalog and export jobs for CSV, Excel, PDF and print.',
    searchableFields: ['name', 'module'],
    filterFields: ['status', 'module', 'format'],
    defaultSort: 'name',
  },
  {
    resource: 'settings',
    title: 'Settings',
    description:
      'Fees, validity, service fee, gateway, SMS, SMTP and system formats.',
    searchableFields: ['key', 'label', 'group'],
    filterFields: ['status', 'group'],
    defaultSort: 'key',
  },
  {
    resource: 'audit-logs',
    title: 'Audit Logs',
    description: 'Admin activity and system workflow audit trail.',
    searchableFields: ['actor', 'action', 'resource', 'resourceId'],
    filterFields: ['resource', 'action'],
    defaultSort: 'createdAt',
  },
];

const base = (
  id: string,
  extra: Omit<DpoRecord, 'id' | 'createdAt' | 'updatedAt'>,
): DpoRecord => ({
  id,
  createdAt: now,
  updatedAt: now,
  ...extra,
});

export const seedData: Record<ResourceName, DpoRecord[]> = {
  members: [
    base('mem_1001', {
      membershipNumber: 'DPO-2025-1001',
      name: 'Ali Raza',
      cnicMasked: '61101-*****-1',
      phone: '0300-1234567',
      membershipType: 'Regular',
      country: 'Pakistan',
      district: 'Lahore',
      paymentStatus: 'paid',
      applicationStatus: 'approved',
      status: 'active',
      issueDate: '2025-05-12',
      expiryDate: '2026-05-11',
      cardNumber: 'CARD-DPO-1001',
    }),
    base('mem_1002', {
      membershipNumber: 'DPO-2025-1002',
      name: 'Sanah Khan',
      cnicMasked: '37405-*****-8',
      phone: '0345-2221908',
      membershipType: 'International',
      country: 'UAE',
      district: 'Dubai',
      paymentStatus: 'paid',
      applicationStatus: 'under_review',
      status: 'pending',
      issueDate: null,
      expiryDate: null,
    }),
    base('mem_1003', {
      membershipNumber: 'DPO-2026-1003',
      name: 'Hassan Ahmed',
      cnicMasked: '35202-*****-2',
      phone: '0320-7883104',
      membershipType: 'General Member',
      country: 'Pakistan',
      district: 'Multan',
      paymentStatus: 'paid',
      applicationStatus: 'approved',
      status: 'active',
      issueDate: '2026-01-05',
      expiryDate: '2027-01-04',
      cardNumber: 'CARD-DPO-1003',
    }),
    base('mem_1004', {
      membershipNumber: 'DPO-2026-1004',
      name: 'Farah Mehmood',
      cnicMasked: '42101-*****-0',
      phone: '0311-9876543',
      membershipType: 'Volunteer Member',
      country: 'Pakistan',
      district: 'Karachi',
      paymentStatus: 'paid',
      applicationStatus: 'approved',
      status: 'active',
      issueDate: '2026-02-12',
      expiryDate: '2027-02-11',
      cardNumber: 'CARD-DPO-1004',
    }),
  ],
  'membership-applications': [
    base('app_1001', {
      applicationNumber: 'APP-2025-1001',
      name: 'Hassan Ahmed',
      cnicMasked: '35202-*****-2',
      phone: '0320-7883104',
      country: 'Pakistan',
      district: 'Multan',
      membershipType: 'Regular',
      paymentStatus: 'paid',
      status: 'pending',
      documents: ['cnic-front.jpg', 'cnic-back.jpg', 'profile.jpg'],
    }),
    base('app_1002', {
      applicationNumber: 'APP-2026-1002',
      name: 'Ayesha Noor',
      cnicMasked: '42201-*****-5',
      phone: '0333-4411200',
      country: 'Pakistan',
      district: 'Karachi',
      membershipType: 'Volunteer Member',
      paymentStatus: 'pending',
      status: 'under_review',
      documents: ['cnic-front.jpg', 'profile.jpg'],
    }),
  ],
  'membership-renewals': [
    base('ren_1001', {
      renewalNumber: 'REN-2025-1001',
      membershipNumber: 'DPO-2024-0881',
      name: 'Farah Mehmood',
      district: 'Karachi',
      paymentStatus: 'paid',
      status: 'under_review',
      requestedExpiryDate: '2027-05-11',
    }),
  ],
  'membership-cards': [
    base('card_1001', {
      cardNumber: 'CARD-DPO-1001',
      membershipNumber: 'DPO-2025-1001',
      name: 'Ali Raza',
      templateVersion: 'membership-v2.1',
      qrValue: 'https://dpo.example/verify/member/DPO-2025-1001',
      status: 'active',
    }),
  ],
  'designation-applications': [
    base('dapp_1001', {
      applicationNumber: 'DSG-APP-1001',
      applicant: 'Ali Raza',
      cnicMasked: '61101-*****-1',
      designation: 'District Coordinator',
      wing: 'Membership',
      province: 'Punjab',
      district: 'Lahore',
      area: 'Model Town',
      paymentStatus: 'paid',
      status: 'pending',
      validityMonths: 12,
    }),
  ],
  'active-designations': [
    base('des_1001', {
      holder: 'Noman Iqbal',
      membershipNumber: 'DPO-2025-0901',
      designation: 'District Coordinator',
      wing: 'Welfare',
      province: 'Sindh',
      district: 'Karachi',
      area: 'Gulshan',
      status: 'active',
      issueDate: '2025-04-01',
      expiryDate: '2026-03-31',
    }),
  ],
  'designation-renewals': [
    base('dren_1001', {
      renewalNumber: 'DSG-REN-1001',
      holder: 'Noman Iqbal',
      designation: 'District Coordinator',
      district: 'Karachi',
      paymentStatus: 'paid',
      status: 'pending',
    }),
  ],
  'designation-master-list': [
    base('dm_1001', {
      designation: 'Chairman',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1002', {
      designation: 'Senior Vice Chairman',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1003', {
      designation: 'Vice Chairman',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1004', {
      designation: 'President',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1005', {
      designation: 'Senior Vice President',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1006', {
      designation: 'Vice President',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1007', {
      designation: 'General Secretary',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1008', {
      designation: 'Joint Secretary',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1009', {
      designation: 'Finance Secretary',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1010', {
      designation: 'Information Secretary',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1011', {
      designation: 'Youth Wing President',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1012', {
      designation: 'Women Wing President',
      amount: 0,
      validityMonths: 12,
      status: 'active',
    }),
  ],
  'geographic-areas': [
    base('area_1001', {
      name: 'Lahore',
      type: 'district',
      country: 'Pakistan',
      province: 'Punjab',
      parentName: 'Lahore Division',
      status: 'active',
    }),
    base('area_1002', {
      name: 'Dubai',
      type: 'international-region',
      country: 'UAE',
      province: 'International',
      parentName: 'Middle East',
      status: 'active',
    }),
  ],
  'wireless-devices': [
    base('wd_1001', {
      imei: '352099001761481',
      brand: 'Samsung',
      model: 'A54',
      serialNumber: 'SN-88421',
      assignedPerson: 'Ali Raza',
      department: 'Verification',
      registrationNumber: 'WD-1001',
      issueDate: '2025-05-12',
      expiryDate: '2026-05-11',
      status: 'active',
    }),
  ],
  complaints: [
    base('cmp_1001', {
      complaintNumber: 'CMP-2025-0718',
      name: 'Ali Raza',
      phone: '0300 1234567',
      category: 'Verification',
      subject: 'CNIC verification issue',
      description: 'CNIC verification issue needs review.',
      status: 'pending',
      publicResponse: null,
    }),
    base('cmp_1002', {
      complaintNumber: 'CMP-2026-0720',
      name: 'Farah Mehmood',
      phone: '0312 7654321',
      category: 'Card Issue',
      subject: 'Membership card correction request',
      description: 'Membership card name correction request.',
      status: 'under_review',
      publicResponse: 'Your card correction request is under review.',
    }),
  ],
  payments: [
    base('pay_1001', {
      orderId: 'ORD-240516-1001',
      gatewayTransactionId: 'TXN-814290',
      user: 'Ali Raza',
      paymentType: 'Membership Fee',
      amount: 2000,
      gateway: 'Manual Transfer',
      status: 'paid',
      paidDate: '2026-07-17',
    }),
    base('pay_1002', {
      orderId: 'ORD-260720-1002',
      gatewayTransactionId: 'TXN-920114',
      user: 'Farah Mehmood',
      paymentType: 'Membership Fee',
      amount: 2000,
      gateway: 'Manual',
      status: 'paid',
      paidDate: '2026-07-20',
    }),
  ],
  'welfare-campaigns': [
    base('wel_1001', {
      title: 'Blood Donation Camp',
      cause: 'Blood donation',
      targetAmount: 500000,
      raisedAmount: 318000,
      startDate: '2026-07-01',
      endDate: '2026-07-31',
      image: 'blood-campaign.jpg',
      status: 'published',
    }),
  ],
  donations: [
    base('don_1001', {
      receiptNumber: 'DON-2025-1001',
      donorName: 'Fahad Noor',
      cause: 'Medical aid',
      amount: 10000,
      paymentStatus: 'paid',
      status: 'active',
    }),
  ],
  'gallery-albums': [
    base('gal_1001', {
      titleEnglish: 'Lahore Membership Camp',
      titleUrdu: 'Lahore camp',
      category: 'Events',
      eventDate: '2026-07-15',
      coverImage: 'camp-cover.jpg',
      imageCount: 34,
      status: 'published',
      images: [
        '/dpo-assets/front-1.png',
        '/dpo-assets/front-2.png',
        '/dpo-assets/front-3.png',
        '/dpo-assets/front-4.png',
      ],
    }),
    base('gal_1002', {
      titleEnglish: 'DPO Awareness Campaign',
      titleUrdu: 'DPO awareness campaign',
      category: 'Campaigns',
      eventDate: '2026-07-20',
      coverImage: '/dpo-assets/front-2.png',
      imageCount: 4,
      status: 'published',
      images: [
        '/dpo-assets/front-1.png',
        '/dpo-assets/front-2.png',
        '/dpo-assets/front-3.png',
        '/dpo-assets/front-4.png',
      ],
    }),
    base('gal_1003', {
      titleEnglish: 'Membership Card Gallery',
      titleUrdu: 'Membership card gallery',
      category: 'Membership',
      eventDate: '2026-07-21',
      coverImage: '/dpo-assets/cms/membership.png',
      imageCount: 3,
      status: 'draft',
      images: [
        '/dpo-assets/cms/membership.png',
        '/dpo-assets/cms/card-logo.png',
        '/dpo-assets/logo-transparent.png',
      ],
    }),
    base('gal_1004', {
      titleEnglish: 'Designation Assets',
      titleUrdu: 'Designation assets',
      category: 'Designations',
      eventDate: '2026-07-21',
      coverImage: '/dpo-assets/cms/designation-idea.png',
      imageCount: 3,
      status: 'published',
      images: [
        '/dpo-assets/cms/designation-idea.png',
        '/dpo-assets/cms/designation-empty.png',
        '/dpo-assets/cms/designation.png',
      ],
    }),
  ],
  'cms-pages': [
    base('cms_home', {
      slug: 'home',
      type: 'page',
      titleEnglish: 'Defenders of Pakistan Organization',
      titleUrdu: 'DPO Home',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'We are a non-profit organization committed to patriotism, national unity, youth empowerment, community welfare, education and human service for a strong, peaceful and progressive Pakistan.',
      seoTitle: 'DPO',
      status: 'published',
      content: {
        heroTitle: 'One Flag\nOne Nation\nOne Pakistan',
        primaryCta: 'Become a Member',
        primaryHref: '/apply/membership',
        secondaryCta: 'Donate Now',
        secondaryHref: '/contact',
        emblemText: 'Pakistan Zindabad',
        bodyEnglish:
          'We are a non-profit organization committed to patriotism, national unity, youth empowerment, community welfare, education and human service for a strong, peaceful and progressive Pakistan.',
        logo: '/dpo-assets/logo-transparent.png',
        favicon: '/favicon.ico',
        image: '/dpo-assets/home-hero-v2.jpg',
        heroSlides: [
          '/dpo-assets/front-1.png',
          '/dpo-assets/front-2.png',
          '/dpo-assets/front-3.png',
          '/dpo-assets/front-4.png',
        ],
        motto: 'One Flag - One Nation - One Pakistan',
        mission:
          'Unite the people of Pakistan through patriotism, education, social welfare and community engagement while empowering youth to become responsible citizens.',
        vision:
          'A united, educated, disciplined and compassionate society where every citizen contributes positively to Pakistan.',
        coreValues: [
          'Patriotism',
          'Unity',
          'Education',
          'Service',
          'Integrity',
          'Leadership',
          'Community Welfare',
          'Respect for Law',
        ],
        items: ['Patriotism', 'Unity', 'Service', 'Empowerment'],
      },
    }),
    base('cms_about', {
      slug: 'about',
      type: 'page',
      titleEnglish: 'Built on service. United by Pakistan.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'A non-profit, non-political and community-driven organization advancing unity, welfare, education and responsible citizenship.',
      status: 'published',
      content: {
        image: '/dpo-assets/home-hero-v2.jpg',
        bodyEnglish:
          'A non-profit, non-political and community-driven organization advancing unity, welfare, education and responsible citizenship.',
        mission:
          'Unite the people of Pakistan through patriotism, education, social welfare and community engagement while empowering youth to become responsible, ethical and productive citizens.',
        vision:
          'To become one of Pakistan trusted and impactful social organizations by creating a united, educated, disciplined and compassionate society.',
        items: [
          'Patriotism',
          'Unity',
          'Education',
          'Service',
          'Integrity',
          'Leadership',
          'Community Welfare',
          'Respect for Law',
        ],
      },
    }),
    base('cms_home_pillars', {
      slug: 'home-pillars',
      type: 'page',
      titleEnglish: 'Home Pillars',
      excerpt: 'Homepage pillar cards.',
      status: 'published',
      content: {
        items: [
          'National strength | Respect for institutions and rule of law.',
          'Youth leadership | Preparing responsible future citizens.',
          'Community service | Welfare without discrimination.',
          'Education | Knowledge, awareness and civic learning.',
          'National unity | One identity across every community.',
        ],
      },
    }),
    base('cms_home_who_we_are', {
      slug: 'home-who-we-are',
      type: 'page',
      titleEnglish: 'A community-driven organization for a stronger Pakistan.',
      image: '/dpo-assets/home-mission-v2.jpg',
      excerpt:
        'DPO works at the grassroots level to create opportunities for positive social participation. Through educational programs, awareness campaigns, community services, welfare projects, leadership development and volunteer activities, the organization encourages unity, discipline, integrity and public service.',
      status: 'published',
      content: {
        eyebrow: 'Who We Are',
        image: '/dpo-assets/home-mission-v2.jpg',
        bodyEnglish:
          'DPO works at the grassroots level to create opportunities for positive social participation. Through educational programs, awareness campaigns, community services, welfare projects, leadership development and volunteer activities, the organization encourages unity, discipline, integrity and public service.',
        sealTitle: 'Service-led',
        sealText: 'Across Pakistan',
        mediaCaption: 'Community. Education. Nation.',
        missionTitle: 'Our mission',
        visionTitle: 'Our vision',
        linkLabel: 'Discover our story',
        linkHref: '/about',
        mission:
          'Unite the people of Pakistan through patriotism, education, social welfare and community engagement while empowering youth to become responsible, ethical and productive citizens.',
        vision:
          'To become one of Pakistan trusted and impactful social organizations by creating a united, educated, disciplined and compassionate society.',
      },
    }),
    base('cms_home_portals', {
      slug: 'home-portals',
      type: 'page',
      titleEnglish: 'Home Portal Cards',
      image: '/dpo-assets/join_mission.png',
      excerpt:
        'Homepage cards for membership, merchandise and quick access.',
      status: 'published',
      content: {
        eyebrow: 'Join our mission',
        image: '/dpo-assets/join_mission.png',
        secondaryImage: '/dpo-assets/merch.png',
        primaryCta: 'Join now',
        primaryHref: '/apply/membership',
        secondaryCta: 'Shop now',
        secondaryHref: '/contact',
        missionFeatures: [
          'Official Membership Card',
          'Priority Invitations',
          'Training & Workshops',
          'Volunteer Opportunities',
        ],
        merchandiseFeatures: [
          'Premium Quality',
          'Official Logo',
          'Nationwide Delivery',
          'Support A Cause',
        ],
        quickEyebrow: 'Quick Access',
        quickLinks: [
          'Membership | /membership',
          'Donate | /contact',
          'Downloads | /legal',
          'Events | /action-plan',
          'Gallery | /gallery',
          'Documents | /legal',
        ],
        items: [
          'Become a Member | Be a part of a patriotic movement for positive change. Together we can build a better Pakistan.',
          'Official Merchandise | Wear your pride. Represent your nation.',
          'All in one place. | Together we can build a stronger, united and progressive Pakistan.',
        ],
      },
    }),
    base('cms_home_impact', {
      slug: 'home-impact',
      type: 'page',
      titleEnglish: 'Progress measured through participation.',
      excerpt:
        'Every number represents people choosing awareness, responsibility and public service.',
      status: 'published',
      content: {
        image: '',
        eyebrow: 'Our growing impact',
        bodyEnglish:
          'Every number represents people choosing awareness, responsibility and public service.',
        items: [
          'Active Members | 10K+',
          'Projects Completed | 250+',
          'Volunteers | 500+',
          'Programs | 7',
        ],
      },
    }),
    base('cms_home_values', {
      slug: 'home-values',
      type: 'page',
      titleEnglish: 'Values that shape every decision.',
      excerpt:
        'Clear principles keep public service accountable, inclusive and focused on long-term national progress.',
      status: 'published',
      content: {
        eyebrow: 'Our Foundation',
        image: '',
        items: [
          'Patriotism | Love, respect and commitment to Pakistan.',
          'Unity | Strengthening harmony among all citizens.',
          'Education | Knowledge as the foundation of national development.',
          'Service | Serving humanity without discrimination.',
          'Integrity | Honesty, transparency and accountability in every action.',
          'Leadership | Developing future leaders through discipline and responsibility.',
          'Community Welfare | Working for sustainable social betterment.',
          'Respect for Law | Supporting constitutional values, justice and citizenship.',
        ],
      },
    }),
    base('cms_home_membership_journey', {
      slug: 'home-membership-journey',
      type: 'page',
      titleEnglish: 'Your service journey starts here.',
      excerpt:
        'A transparent path from choosing your membership type to receiving an official, verifiable identity.',
      status: 'published',
      content: {
        eyebrow: 'Membership',
        image: '',
        primaryCta: 'Start membership application',
        primaryHref: '/apply/membership',
        items: [
          'Choose your path | Select the membership type that matches your role and commitment.',
          'Verify details | Submit the required identity and contact information securely.',
          'Receive your card | Approved members receive a clear, official membership identity.',
          'Begin serving | Take part in programs, campaigns and community initiatives.',
        ],
      },
    }),
    base('cms_home_cta', {
      slug: 'home-cta',
      type: 'page',
      titleEnglish: 'Build the future through service.',
      excerpt:
        'Explore DPO membership, leadership roles and national programs, then choose where your contribution can matter most.',
      status: 'published',
      content: {
        eyebrow: 'Next Step',
        image: '',
        bodyEnglish:
          'Explore DPO membership, leadership roles and national programs, then choose where your contribution can matter most.',
        primaryCta: 'Join the organization',
        primaryHref: '/membership',
        secondaryCta: 'Talk to our team',
        secondaryHref: '/contact',
      },
    }),
    base('cms_action_plan', {
      slug: 'action-plan',
      type: 'page',
      titleEnglish: 'Seven priorities. One national direction.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'One Flag, One Nation, One Pakistan becomes a practical civic roadmap across institutions, unity, education, digital responsibility and public welfare.',
      status: 'published',
      content: {
        eyebrow: '7-Point Action Plan',
        primaryCta: 'Explore the plan',
        primaryHref: '/action-plan',
        image: '/dpo-assets/front-2.png',
        bodyEnglish:
          'Each priority supports the next. Strong institutions need responsible citizens; responsible citizens need awareness, unity and opportunity.',
        items: [
          'Strengthening National Institutions',
          'Promoting Unity',
          'One Nation, One Identity',
          'Rule of Law',
          'Civic Education',
          'Digital Awareness',
          'Prosperous Pakistan',
        ],
      },
    }),
    base('cms_membership', {
      slug: 'membership',
      type: 'page',
      titleEnglish: 'Belong to something built on service.',
      image: '/dpo-assets/home-mission-v2.jpg',
      excerpt:
        'Understand the required documents, terms, fee and approval journey before submitting your application.',
      status: 'published',
      content: {
        eyebrow: 'Membership',
        index: '03',
        image: '/dpo-assets/home-mission-v2.jpg',
        bodyEnglish:
          'Understand the required documents, terms, fee and approval journey before submitting your application.',
      },
    }),
    base('cms_membership_summary', {
      slug: 'membership-summary',
      type: 'page',
      titleEnglish: 'Membership Summary',
      status: 'published',
      content: {
        memberLabel: 'Membership',
        memberValue: 'Simple Member',
        feeLabel: 'Membership fee',
        feeValue: 'PKR 2,000',
        validityLabel: 'Validity',
        validityValue: 'One year',
        documentsLabel: 'Required documents',
        documentsValue: '5 items',
      },
    }),
    base('cms_membership_readiness', {
      slug: 'membership-readiness',
      type: 'page',
      titleEnglish: 'Prepare once. Apply with confidence.',
      excerpt:
        'Keeping the right information ready reduces delays and makes verification easier for the administration team.',
      status: 'published',
      content: {
        eyebrow: 'Application Readiness',
        image: '',
        bodyEnglish:
          'Keeping the right information ready reduces delays and makes verification easier for the administration team.',
        documentsTitle: 'Required documents',
        fieldsTitle: 'Application information',
        panelEyebrow: 'Approval journey',
        panelTitle: 'Four clear steps to membership.',
        primaryCta: 'Ask about applying',
        primaryHref: '/contact',
        items: [
          'Provide personal details',
          'Upload required documents',
          'Administrative review and approval',
          'Receive official member identity',
        ],
        formFields: [
          'Name',
          'Father/guardian name',
          'CNIC/B-Form',
          'Date of birth',
          'Mobile',
          'Email',
          'Address',
          'City',
          'Photo',
          'Consent/signature',
        ],
      },
    }),
    base('cms_membership_card', {
      slug: 'membership-card',
      type: 'page',
      titleEnglish: 'A membership card designed for trust.',
      excerpt:
        'Approved identity details, validity and verification information should remain clear while sensitive personal information stays protected.',
      status: 'published',
      content: {
        eyebrow: 'Official Identity',
        image: '',
        bodyEnglish:
          'Approved identity details, validity and verification information should remain clear while sensitive personal information stays protected.',
        frontTitle: 'Front side',
        backTitle: 'Back side',
        primaryCta: 'Explore card design',
        primaryHref: '/card-design',
        frontItems: [
          'Organization logo',
          'Member photo',
          'Member name',
          'Membership ID',
          'Designation',
        ],
        backItems: [
          'QR code',
          'Emergency contact',
          'Card validity',
          'Official website',
          'Brief terms and conditions',
        ],
      },
    }),
    base('cms_membership_responsibility', {
      slug: 'membership-responsibility',
      type: 'page',
      titleEnglish: 'Membership is a commitment, not just a card.',
      excerpt:
        "Every member is expected to protect the organization's purpose, trust and public reputation.",
      status: 'published',
      content: {
        eyebrow: 'Member Responsibility',
        image: '',
        bodyEnglish:
          "Every member is expected to protect the organization's purpose, trust and public reputation.",
        terms: [
          'Every member must follow the organization constitution, code of conduct and policies.',
          'Incorrect or incomplete information may lead to rejection or cancellation.',
          'Membership approval remains subject to the authorized organization committee.',
          'Activities against the reputation or purpose of the organization are not acceptable.',
        ],
        items: [
          'Every member must follow the organization constitution, code of conduct and policies.',
          'Incorrect or incomplete information may lead to rejection or cancellation.',
          'Membership approval remains subject to the authorized organization committee.',
          'Activities against the reputation or purpose of the organization are not acceptable.',
        ],
      },
    }),
    base('cms_membership_cta', {
      slug: 'membership-cta',
      type: 'page',
      titleEnglish: 'Ready to begin your membership journey?',
      excerpt:
        'Keep your identity documents ready and complete the guided online application for administrative review.',
      status: 'published',
      content: {
        eyebrow: 'Next Step',
        image: '',
        bodyEnglish:
          'Keep your identity documents ready and complete the guided online application for administrative review.',
        primaryCta: 'Apply for membership',
        primaryHref: '/apply/membership',
        secondaryCta: 'Track an application',
        secondaryHref: '/application-status',
      },
    }),
    base('cms_designations', {
      slug: 'designations',
      type: 'page',
      titleEnglish: 'Clear roles. Accountable leadership.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'Explore DPO public designation structure, role responsibilities and the principles used for controlled leadership allocation.',
      status: 'published',
      content: {
        image: '/dpo-assets/cms/designation-idea.png',
        bodyEnglish:
          'A designation represents a duty to organize, communicate and serve. Every appointment should be based on capability, local need and organizational approval.',
        items: [
          'Transparent review by authorized administration',
          'Clear responsibilities for every role',
          'No duplicate active designation in the same area',
          'Official branding on approved letters and identity cards',
        ],
      },
    }),
    base('cms_designations_metrics', {
      slug: 'designations-metrics',
      type: 'page',
      titleEnglish: 'Designation Metrics',
      status: 'published',
      content: {
        rolesLabel: 'Published roles',
        rolesValue: '33',
        feeLabel: 'Designation fee',
        feeValue: 'As configured',
        durationLabel: 'Appointment duration',
        durationValue: 'As configured',
      },
    }),
    base('cms_card_design', {
      slug: 'card-design',
      type: 'page',
      titleEnglish: 'Designed for recognition and trust.',
      image: '/dpo-assets/home-mission-v2.jpg',
      excerpt:
        'A professional card system that balances clear public verification with responsible protection of member information.',
      status: 'published',
      content: {
        image: '/dpo-assets/home-mission-v2.jpg',
        bodyEnglish:
          'The sample uses the supplied DPO identity while keeping the final member information structured, legible and easy to verify.',
        frontItems: [
          'Organization logo',
          'Member photo',
          'Member name',
          'Membership ID',
          'Designation',
        ],
        backItems: [
          'QR code',
          'Emergency contact',
          'Card validity',
          'Official website',
          'Brief terms and conditions',
        ],
      },
    }),
    base('cms_gallery', {
      slug: 'gallery',
      type: 'page',
      titleEnglish: 'Moments of unity, action and service.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'A structured public archive for DPO events, campaigns, programs and official visual references.',
      status: 'published',
      content: { image: '/dpo-assets/home-hero-v2.jpg' },
    }),
    base('cms_legal', {
      slug: 'legal',
      type: 'page',
      titleEnglish: 'Clear policies build public trust.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'Review how DPO handles website use, member information, identity records, payments, refunds and donations.',
      status: 'published',
      content: { image: '/dpo-assets/home-hero-v2.jpg' },
    }),
    base('cms_contact', {
      slug: 'contact',
      type: 'page',
      titleEnglish: 'Start a meaningful conversation.',
      image: '/dpo-assets/home-mission-v2.jpg',
      excerpt:
        'Reach the organization for membership guidance, designation questions, partnerships, welfare coordination or general information.',
      status: 'published',
      content: { image: '/dpo-assets/home-mission-v2.jpg' },
    }),
    base('cms_member_services', {
      slug: 'member-services',
      type: 'page',
      titleEnglish: 'Verification and support in one place.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'Verify a member, request renewal, replace a card or submit a complaint through the connected DPO administration system.',
      status: 'published',
      content: {
        eyebrow: 'Member Services',
        index: 'SERVICES',
        image: '/dpo-assets/home-hero-v2.jpg',
        bodyEnglish:
          'Verify a member, request renewal, replace a card or submit a complaint through the connected DPO administration system.',
      },
    }),
    base('cms_member_services_renewal', {
      slug: 'member-services-renewal',
      type: 'page',
      titleEnglish: 'Request membership renewal',
      excerpt:
        'Active or expired members can send a renewal request for admin review.',
      status: 'published',
      content: {
        bodyEnglish:
          'Active or expired members can send a renewal request for admin review.',
        identifierLabel: 'Membership number',
        identifierPlaceholder: 'DPO-2026-1001',
        expiryLabel: 'Requested expiry date',
        documentLabel: 'Supporting document',
        documentName: 'Renewal Supporting Document',
        submitButton: 'Submit renewal',
        secureNote:
          'Securely recorded for authorized administrative review.',
        notEligibleMessage: 'This membership is not eligible for renewal.',
        successTitle: 'Renewal request submitted',
        successPrefix: 'Reference',
        successText: 'Payment remains pending until confirmed by DPO.',
        errorTitle: 'Renewal could not be submitted',
        errorText: 'Please check the membership number.',
      },
    }),
    base('cms_application_status', {
      slug: 'application-status',
      type: 'page',
      titleEnglish: 'Follow your application review.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'Use your CNIC to check payment, document and administrative status.',
      status: 'published',
      content: { image: '/dpo-assets/home-hero-v2.jpg' },
    }),
    base('cms_membership_application', {
      slug: 'membership-application',
      type: 'page',
      titleEnglish: 'Become an official DPO member.',
      image: '/dpo-assets/home-mission-v2.jpg',
      excerpt:
        'Complete the guided application, upload your verification documents and receive an application number for tracking.',
      status: 'published',
      content: { image: '/dpo-assets/home-mission-v2.jpg' },
    }),
    base('cms_designation_application', {
      slug: 'designation-application',
      type: 'page',
      titleEnglish: 'Apply to serve in a leadership role.',
      image: '/dpo-assets/home-hero-v2.jpg',
      excerpt:
        'Choose an active designation, provide your area details and submit the documents required for formal review.',
      status: 'published',
      content: {
        eyebrow: 'Designation Application',
        index: 'APPLY',
        image: '/dpo-assets/home-hero-v2.jpg',
        bodyEnglish:
          'Choose an active designation, provide your area details and submit the documents required for formal review.',
        progressLabel: 'Application progress',
        formTitle: 'Apply for a designation',
        formText: 'Your details remain editable until the final submission.',
        privacyNote:
          'CNIC is masked in application records. Original files remain available only for authorized review.',
        stepPrefix: 'Step',
        formSteps: ['Role', 'Personal details', 'Location', 'Documents'],
        stepTitles: [
          'Choose a leadership role',
          'Tell us about yourself',
          'Confirm the requested area',
          'Upload verification documents',
        ],
        stepDescriptions: [
          'Select an available designation and share your relevant experience.',
          'Use accurate identity and contact information for administrative review.',
          'Designation availability is checked by district and local area.',
          'The admin team will verify each document before making a decision.',
        ],
        previousButton: 'Previous',
        nextButton: 'Continue',
        submitButton: 'Submit application',
        submittingText: 'Submitting',
        documentsAlertTitle: 'Document privacy',
        documentsAlertText:
          'Upload clear images. Each file can be up to 5 MB and will remain pending until an authorized admin reviews it.',
        cnicFrontLabel: 'CNIC front',
        cnicBackLabel: 'CNIC back',
        photoLabel: 'Profile photo',
        termsIntro: 'I confirm that the information is correct and I agree to the',
        termsLabel: 'terms and conditions',
        privacyLabel: 'CNIC privacy policy',
      },
    }),
  ],
  'card-templates': [
    base('tmpl_1001', {
      name: 'Membership Card v2.1',
      templateType: 'membership',
      version: '2.1',
      dimensions: '85.60 x 54.00 mm',
      logo: '/dpo-assets/logo-transparent.png',
      cardLogo: '/dpo-assets/logo.png',
      qrPosition: 'right',
      requiredFrontFields: [
        'organizationLogo',
        'memberPhoto',
        'memberName',
        'membershipId',
        'designation',
      ],
      requiredBackFields: [
        'qrCode',
        'emergencyContact',
        'cardValidity',
        'officialWebsite',
        'termsAndConditions',
      ],
      status: 'active',
    }),
  ],
  'notification-templates': [
    base('nt_1001', {
      name: 'Application Approved',
      event: 'application_approved',
      channel: 'sms',
      subject: 'Application Approved',
      bodyEnglish: 'Your DPO application has been approved.',
      bodyUrdu: 'Your DPO application has been approved.',
      variables: ['name', 'membershipNumber'],
      status: 'active',
    }),
  ],
  'notification-logs': [],
  'admin-users': [
    base('admin_1001', {
      name: 'Super Admin',
      email: 'admin@dpo.local',
      passwordHash:
        'scrypt:dpo-admin-seed-2026:aa4a4b706ef666481179cd9111b9362434a77faab86b2aa86731c1c1552392258b7eda7f45409328c7f4139552489a95474dd8da3a3ab9c449572a153b23ba2d',
      role: 'Super Admin',
      status: 'active',
      lastLoginAt: now,
    }),
    base('admin_1002', {
      name: 'Super Admin',
      email: 'admin@dpo.org.pk',
      passwordHash:
        'scrypt:dpo-admin-seed-2026:aa4a4b706ef666481179cd9111b9362434a77faab86b2aa86731c1c1552392258b7eda7f45409328c7f4139552489a95474dd8da3a3ab9c449572a153b23ba2d',
      role: 'Super Admin',
      status: 'active',
      lastLoginAt: now,
    }),
  ],
  roles: [
    base('role_super_admin', {
      name: 'Super Admin',
      description: 'Full system access',
      permissions: ['*'],
      status: 'active',
    }),
    base('role_membership_manager', {
      name: 'Membership Manager',
      description: 'Membership approval and card management',
      permissions: [
        'members.view',
        'members.approve',
        'members.edit',
        'members.export',
      ],
      status: 'active',
    }),
  ],
  reports: [
    base('rpt_1001', {
      name: 'Member registration report',
      module: 'members',
      format: 'pdf',
      status: 'active',
      lastRunAt: now,
    }),
  ],
  settings: [
    base('set_org_official_name', {
      key: 'organization_official_name',
      label: 'Official organization name',
      group: 'organization',
      value: 'Defenders of Pakistan Organization (DPO)',
      status: 'active',
    }),
    base('set_org_office_address', {
      key: 'organization_office_address',
      label: 'Office address',
      group: 'organization',
      value:
        'Office no: 143, Street no: 08 Defense Officers Scheme no: 1, Malir Cantt, Karachi',
      status: 'active',
    }),
    base('set_org_phone', {
      key: 'organization_phone',
      label: 'Phone',
      group: 'organization',
      value: '+92 300 1234567',
      status: 'active',
    }),
    base('set_org_email', {
      key: 'organization_email',
      label: 'Email',
      group: 'organization',
      value: 'info@defendersofpakistan.org',
      status: 'active',
    }),
    base('set_org_motto', {
      key: 'organization_motto',
      label: 'Motto',
      group: 'organization',
      value: 'One Flag | One Nation | One Pakistan',
      status: 'active',
    }),
    base('set_brand_logo_path', {
      key: 'brand_logo_path',
      label: 'Brand logo path',
      group: 'branding',
      value: '/dpo-assets/logo-transparent.png',
      status: 'active',
    }),
    base('set_brand_favicon_path', {
      key: 'brand_favicon_path',
      label: 'Brand favicon path',
      group: 'branding',
      value: '/favicon.ico',
      status: 'active',
    }),
    base('set_membership_types', {
      key: 'membership_types',
      label: 'Membership',
      group: 'membership',
      value: ['Member'],
      status: 'active',
    }),
    base('set_membership_required_documents', {
      key: 'membership_required_documents',
      label: 'Required membership documents',
      group: 'membership',
      value: [
        'CNIC or B-Form',
        'Passport size photo',
        'Mobile number',
        'Email address',
        'Residential address',
      ],
      status: 'active',
    }),
    base('set_membership_fee_pk', {
      key: 'membership_fee_pk',
      label: 'Membership fee PK',
      group: 'fees',
      value: 2000,
      status: 'active',
    }),
    base('set_service_fee', {
      key: 'service_fee_percent',
      label: '15% service fee',
      group: 'fees',
      value: 15,
      status: 'active',
    }),
    base('set_payment_account_title', {
      key: 'payment_account_title',
      label: 'Payment account title',
      group: 'payments',
      value: 'Defenders of Pakistan Organization',
      status: 'active',
    }),
    base('set_payment_bank_name', {
      key: 'payment_bank_name',
      label: 'Bank name',
      group: 'payments',
      value: 'Bank name to be updated',
      status: 'active',
    }),
    base('set_payment_account_number', {
      key: 'payment_account_number',
      label: 'Account number',
      group: 'payments',
      value: '000000000000',
      status: 'active',
    }),
    base('set_payment_iban', {
      key: 'payment_iban',
      label: 'IBAN',
      group: 'payments',
      value: 'PK00BANK0000000000000000',
      status: 'active',
    }),
    base('set_payment_instructions_note', {
      key: 'payment_instructions_note',
      label: 'Payment note',
      group: 'payments',
      value:
        'Transfer the fee to this account and keep the receipt. Admin will verify payment manually before approval.',
      status: 'active',
    }),
  ],
  'audit-logs': [
    base('aud_1001', {
      actor: 'system',
      action: 'seed',
      resource: 'system',
      resourceId: 'bootstrap',
      ipAddress: '127.0.0.1',
      userAgent: 'server-seed',
    }),
  ],
};
