import { DpoRecord, ResourceName, ResourceSchema } from './dpo.types';

const now = new Date('2026-07-17T12:00:00.000Z').toISOString();

export const resourceSchemas: ResourceSchema[] = [
  {
    resource: 'members',
    title: 'Members Management',
    description:
      'Approved and active DPO members with card and renewal lifecycle.',
    searchableFields: [
      'membershipNumber',
      'name',
      'cnicMasked',
      'phone',
      'district',
    ],
    filterFields: [
      'status',
      'paymentStatus',
      'country',
      'district',
      'membershipType',
    ],
    defaultSort: 'createdAt',
  },
  {
    resource: 'membership-applications',
    title: 'Membership Applications',
    description: 'Public membership applications pending review and approval.',
    searchableFields: ['applicationNumber', 'name', 'cnicMasked', 'phone'],
    filterFields: ['status', 'paymentStatus', 'country', 'district'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'membership-renewals',
    title: 'Membership Renewals',
    description: 'Membership renewal and card regeneration requests.',
    searchableFields: ['renewalNumber', 'membershipNumber', 'name'],
    filterFields: ['status', 'paymentStatus', 'district'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'membership-cards',
    title: 'Membership Cards',
    description: 'Generated, regenerated and downloadable membership cards.',
    searchableFields: ['cardNumber', 'membershipNumber', 'name'],
    filterFields: ['status', 'templateVersion'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'designation-applications',
    title: 'Designation Applications',
    description:
      'Designation applications, duplicate-area validation and approval workflow.',
    searchableFields: ['applicationNumber', 'applicant', 'designation', 'area'],
    filterFields: ['status', 'paymentStatus', 'province', 'district', 'wing'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'active-designations',
    title: 'Active Designations',
    description: 'Current designation holders and assigned areas.',
    searchableFields: ['holder', 'designation', 'area', 'membershipNumber'],
    filterFields: ['status', 'province', 'district', 'wing'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'designation-renewals',
    title: 'Designation Renewals',
    description: 'Designation renewal payment and approval workflow.',
    searchableFields: ['renewalNumber', 'holder', 'designation'],
    filterFields: ['status', 'paymentStatus', 'district'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'designation-master-list',
    title: 'Designation Master List',
    description: 'Allowed designations, wings, fees and validity duration.',
    searchableFields: ['designation', 'wing'],
    filterFields: ['status', 'wing'],
    defaultSort: 'designation',
  },
  {
    resource: 'geographic-areas',
    title: 'Geographic Area Management',
    description:
      'Country, province, division, district, tehsil, union council and city hierarchy.',
    searchableFields: ['name', 'type', 'parentName'],
    filterFields: ['status', 'type', 'country', 'province'],
    defaultSort: 'name',
  },
  {
    resource: 'wireless-devices',
    title: 'Wireless Device Management',
    description:
      'IMEI, serial number, assignment, renewal, lost and blocked device workflow.',
    searchableFields: [
      'imei',
      'brand',
      'model',
      'serialNumber',
      'assignedPerson',
    ],
    filterFields: ['status', 'department'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'complaints',
    title: 'Complaint Management',
    description:
      'Complaint assignment, priority, SLA, public response and internal notes.',
    searchableFields: ['complaintNumber', 'name', 'cnicMasked', 'subject'],
    filterFields: [
      'status',
      'category',
      'priority',
      'assignedOfficer',
      'region',
    ],
    defaultSort: 'createdAt',
  },
  {
    resource: 'payments',
    title: 'Payments & Finance',
    description:
      'Transactions, callbacks, offline payments, service fee, receipts and refunds.',
    searchableFields: [
      'orderId',
      'gatewayTransactionId',
      'user',
      'paymentType',
    ],
    filterFields: ['status', 'gateway', 'paymentType', 'refundStatus'],
    defaultSort: 'paidDate',
  },
  {
    resource: 'welfare-campaigns',
    title: 'Welfare Campaigns',
    description:
      'Causes, campaigns, targets, publishing and cause-wise analytics.',
    searchableFields: ['title', 'cause'],
    filterFields: ['status', 'cause'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'donations',
    title: 'Donation Records',
    description: 'Donation receipts, donors, causes and payment status.',
    searchableFields: ['donorName', 'receiptNumber', 'cause'],
    filterFields: ['status', 'cause', 'paymentStatus'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'gallery-albums',
    title: 'Gallery Admin',
    description:
      'Albums, images, bilingual title, cover image, ordering and publishing.',
    searchableFields: ['titleEnglish', 'titleUrdu'],
    filterFields: ['status', 'category'],
    defaultSort: 'eventDate',
  },
  {
    resource: 'cms-pages',
    title: 'Website CMS',
    description:
      'Logo, hero slides, policies, footer, links, SEO and bilingual content.',
    searchableFields: ['slug', 'titleEnglish', 'titleUrdu'],
    filterFields: ['status', 'type'],
    defaultSort: 'slug',
  },
  {
    resource: 'card-templates',
    title: 'Card Template Management',
    description:
      'Membership and designation card front/back template versions.',
    searchableFields: ['name', 'templateType', 'version'],
    filterFields: ['status', 'templateType'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'notification-templates',
    title: 'Notification Templates',
    description:
      'Email, SMS and WhatsApp placeholder templates with variables.',
    searchableFields: ['name', 'channel', 'event'],
    filterFields: ['status', 'channel', 'event'],
    defaultSort: 'name',
  },
  {
    resource: 'notification-logs',
    title: 'Notification Logs',
    description: 'Delivery logs, failed retries and manual/bulk send history.',
    searchableFields: ['recipient', 'channel', 'event'],
    filterFields: ['status', 'channel'],
    defaultSort: 'createdAt',
  },
  {
    resource: 'admin-users',
    title: 'Admin Users',
    description: 'Admin accounts, roles, statuses and last login.',
    searchableFields: ['name', 'email', 'role'],
    filterFields: ['status', 'role'],
    defaultSort: 'name',
  },
  {
    resource: 'roles',
    title: 'Roles & Permissions',
    description: 'Role definitions and permission matrices.',
    searchableFields: ['name', 'description'],
    filterFields: ['status'],
    defaultSort: 'name',
  },
  {
    resource: 'reports',
    title: 'Reports',
    description:
      'Report catalog and export jobs for CSV, Excel, PDF and print.',
    searchableFields: ['name', 'module'],
    filterFields: ['status', 'module', 'format'],
    defaultSort: 'name',
  },
  {
    resource: 'settings',
    title: 'Settings',
    description:
      'Fees, validity, service fee, gateway, SMS, SMTP and system formats.',
    searchableFields: ['key', 'label', 'group'],
    filterFields: ['status', 'group'],
    defaultSort: 'key',
  },
  {
    resource: 'audit-logs',
    title: 'Audit Logs',
    description: 'Admin activity and system workflow audit trail.',
    searchableFields: ['actor', 'action', 'resource', 'resourceId'],
    filterFields: ['resource', 'action'],
    defaultSort: 'createdAt',
  },
];

const base = (
  id: string,
  extra: Omit<DpoRecord, 'id' | 'createdAt' | 'updatedAt'>,
): DpoRecord => ({
  id,
  createdAt: now,
  updatedAt: now,
  ...extra,
});

export const seedData: Record<ResourceName, DpoRecord[]> = {
  members: [
    base('mem_1001', {
      membershipNumber: 'DPO-2025-1001',
      name: 'Ali Raza',
      cnicMasked: '61101-*****-1',
      phone: '0300-1234567',
      membershipType: 'Regular',
      country: 'Pakistan',
      district: 'Lahore',
      paymentStatus: 'paid',
      applicationStatus: 'approved',
      status: 'active',
      issueDate: '2025-05-12',
      expiryDate: '2026-05-11',
      cardNumber: 'CARD-DPO-1001',
    }),
    base('mem_1002', {
      membershipNumber: 'DPO-2025-1002',
      name: 'Sanah Khan',
      cnicMasked: '37405-*****-8',
      phone: '0345-2221908',
      membershipType: 'International',
      country: 'UAE',
      district: 'Dubai',
      paymentStatus: 'paid',
      applicationStatus: 'under_review',
      status: 'pending',
      issueDate: null,
      expiryDate: null,
    }),
  ],
  'membership-applications': [
    base('app_1001', {
      applicationNumber: 'APP-2025-1001',
      name: 'Hassan Ahmed',
      cnicMasked: '35202-*****-2',
      phone: '0320-7883104',
      country: 'Pakistan',
      district: 'Multan',
      membershipType: 'Regular',
      paymentStatus: 'paid',
      status: 'pending',
      documents: ['cnic-front.jpg', 'cnic-back.jpg', 'profile.jpg'],
    }),
  ],
  'membership-renewals': [
    base('ren_1001', {
      renewalNumber: 'REN-2025-1001',
      membershipNumber: 'DPO-2024-0881',
      name: 'Farah Mehmood',
      district: 'Karachi',
      paymentStatus: 'paid',
      status: 'under_review',
      requestedExpiryDate: '2027-05-11',
    }),
  ],
  'membership-cards': [
    base('card_1001', {
      cardNumber: 'CARD-DPO-1001',
      membershipNumber: 'DPO-2025-1001',
      name: 'Ali Raza',
      templateVersion: 'membership-v2.1',
      qrValue: 'https://dpo.example/verify/member/DPO-2025-1001',
      status: 'active',
    }),
  ],
  'designation-applications': [
    base('dapp_1001', {
      applicationNumber: 'DSG-APP-1001',
      applicant: 'Ali Raza',
      cnicMasked: '61101-*****-1',
      designation: 'District Coordinator',
      wing: 'Membership',
      province: 'Punjab',
      district: 'Lahore',
      area: 'Model Town',
      paymentStatus: 'paid',
      status: 'pending',
      validityMonths: 12,
    }),
  ],
  'active-designations': [
    base('des_1001', {
      holder: 'Noman Iqbal',
      membershipNumber: 'DPO-2025-0901',
      designation: 'District Coordinator',
      wing: 'Welfare',
      province: 'Sindh',
      district: 'Karachi',
      area: 'Gulshan',
      status: 'active',
      issueDate: '2025-04-01',
      expiryDate: '2026-03-31',
    }),
  ],
  'designation-renewals': [
    base('dren_1001', {
      renewalNumber: 'DSG-REN-1001',
      holder: 'Noman Iqbal',
      designation: 'District Coordinator',
      district: 'Karachi',
      paymentStatus: 'paid',
      status: 'pending',
    }),
  ],
  'designation-master-list': [
    base('dm_1001', {
      designation: 'District Coordinator',
      wing: 'Membership',
      feePk: 5000,
      feeInternational: 35,
      validityMonths: 12,
      status: 'active',
    }),
    base('dm_1002', {
      designation: 'Complaint Officer',
      wing: 'Complaint',
      feePk: 3500,
      feeInternational: 25,
      validityMonths: 12,
      status: 'active',
    }),
  ],
  'geographic-areas': [
    base('area_1001', {
      name: 'Lahore',
      type: 'district',
      country: 'Pakistan',
      province: 'Punjab',
      parentName: 'Lahore Division',
      status: 'active',
    }),
    base('area_1002', {
      name: 'Dubai',
      type: 'international-region',
      country: 'UAE',
      province: 'International',
      parentName: 'Middle East',
      status: 'active',
    }),
  ],
  'wireless-devices': [
    base('wd_1001', {
      imei: '352099001761481',
      brand: 'Samsung',
      model: 'A54',
      serialNumber: 'SN-88421',
      assignedPerson: 'Ali Raza',
      department: 'Verification',
      registrationNumber: 'WD-1001',
      issueDate: '2025-05-12',
      expiryDate: '2026-05-11',
      status: 'active',
    }),
  ],
  complaints: [
    base('cmp_1001', {
      complaintNumber: 'CMP-2025-0718',
      name: 'Ali Raza',
      cnicMasked: '61101-*****-1',
      category: 'Verification',
      priority: 'high',
      subject: 'CNIC verification issue',
      status: 'pending',
      assignedOfficer: 'A. Shahid',
      submittedDate: '2026-07-17',
      slaDueAt: '2026-07-18T12:00:00.000Z',
      publicResponse: null,
      internalNotes: [],
    }),
  ],
  payments: [
    base('pay_1001', {
      orderId: 'ORD-240516-1001',
      gatewayTransactionId: 'TXN-814290',
      user: 'Ali Raza',
      paymentType: 'Membership Fee',
      baseAmount: 1700,
      serviceFee: 300,
      totalAmount: 2000,
      gateway: 'JazzCash',
      status: 'paid',
      paidDate: '2026-07-17',
      refundStatus: 'none',
    }),
  ],
  'welfare-campaigns': [
    base('wel_1001', {
      title: 'Blood Donation Camp',
      cause: 'Blood donation',
      targetAmount: 500000,
      raisedAmount: 318000,
      startDate: '2026-07-01',
      endDate: '2026-07-31',
      image: 'blood-campaign.jpg',
      status: 'published',
    }),
  ],
  donations: [
    base('don_1001', {
      receiptNumber: 'DON-2025-1001',
      donorName: 'Fahad Noor',
      cause: 'Medical aid',
      amount: 10000,
      paymentStatus: 'paid',
      status: 'active',
    }),
  ],
  'gallery-albums': [
    base('gal_1001', {
      titleEnglish: 'Lahore Membership Camp',
      titleUrdu: 'Lahore camp',
      category: 'Events',
      eventDate: '2026-07-15',
      coverImage: 'camp-cover.jpg',
      imageCount: 34,
      status: 'published',
    }),
  ],
  'cms-pages': [
    base('cms_home', {
      slug: 'home',
      type: 'page',
      titleEnglish: 'Defender of Pakistan Organization',
      titleUrdu: 'DPO Home',
      seoTitle: 'DPO',
      status: 'published',
      content: {
        heroSlides: [],
        mission: 'Service, verification and public support.',
      },
    }),
  ],
  'card-templates': [
    base('tmpl_1001', {
      name: 'Membership Card v2.1',
      templateType: 'membership',
      version: '2.1',
      dimensions: '85.60 x 54.00 mm',
      qrPosition: 'right',
      status: 'active',
    }),
  ],
  'notification-templates': [
    base('nt_1001', {
      name: 'Application Approved',
      event: 'application_approved',
      channel: 'sms',
      subject: 'Application Approved',
      bodyEnglish: 'Your DPO application has been approved.',
      bodyUrdu: 'Your DPO application has been approved.',
      variables: ['name', 'membershipNumber'],
      status: 'active',
    }),
  ],
  'notification-logs': [
    base('nl_1001', {
      recipient: '0300-1234567',
      channel: 'sms',
      event: 'payment_successful',
      status: 'active',
      sentAt: now,
    }),
  ],
  'admin-users': [
    base('admin_1001', {
      name: 'Super Admin',
      email: 'admin@dpo.local',
      role: 'Super Admin',
      status: 'active',
      lastLoginAt: now,
    }),
  ],
  roles: [
    base('role_super_admin', {
      name: 'Super Admin',
      description: 'Full system access',
      permissions: ['*'],
      status: 'active',
    }),
    base('role_membership_manager', {
      name: 'Membership Manager',
      description: 'Membership approval and card management',
      permissions: [
        'members.view',
        'members.approve',
        'members.edit',
        'members.export',
      ],
      status: 'active',
    }),
  ],
  reports: [
    base('rpt_1001', {
      name: 'Member registration report',
      module: 'members',
      format: 'pdf',
      status: 'active',
      lastRunAt: now,
    }),
  ],
  settings: [
    base('set_membership_fee_pk', {
      key: 'membership_fee_pk',
      label: 'Membership fee PK',
      group: 'fees',
      value: 2000,
      status: 'active',
    }),
    base('set_service_fee', {
      key: 'service_fee_percent',
      label: '15% service fee',
      group: 'fees',
      value: 15,
      status: 'active',
    }),
  ],
  'audit-logs': [
    base('aud_1001', {
      actor: 'system',
      action: 'seed',
      resource: 'system',
      resourceId: 'bootstrap',
      ipAddress: '127.0.0.1',
      userAgent: 'server-seed',
    }),
  ],
};
